
export default function Home() {
  return (
    <>
      <main>
        <section className="bg-[#254f1a] min-h-screen">
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>
          <div>Main</div>

        </section>
      </main>
    </>
  );
}
